export const services = [
 {slug:'enregistrement-vocal',title:'Enregistrement vocal',eyebrow:'La prise',short_description:'Une voix au centre, accompagnée du début à la fin.',description:'Prise de voix assistée avec direction artistique, conseils de placement vocal, cabine traitée acoustiquement et chaîne d’enregistrement professionnelle.',price_label:'2 000 DA',price_unit:'/ heure',features:['Direction artistique','Cabine traitée','Prise assistée']},
 {slug:'mixage-mastering',title:'Mixage & mastering',eyebrow:'La finition',short_description:'Un morceau équilibré, prêt à sortir.',description:'Égalisation, compression, nettoyage fréquentiel, spatialisation, équilibre instrumental, traitement vocal, réverbérations, délais et mastering adapté aux plateformes de streaming.',price_label:'7 000 DA',price_unit:'/ titre',features:['Traitement vocal','Mixage stéréo','Master streaming']},
 {slug:'beatmaking-composition',title:'Beatmaking & composition',eyebrow:'La production',short_description:'Des prods façonnées autour de votre identité.',description:'Productions exclusives et personnalisées selon la voix, le style et l’identité de l’artiste. Raï, rap, trap, RnB, Zan9aoui, afro et drill. Instruments live possibles : trompette, violon et derbouka.',price_label:'7 000 DA',price_unit:'/ beat',features:['Raï · Rap · Trap · RnB','Afro · Drill · Zan9aoui','Instruments live en option']},
 {slug:'topline-ecriture',title:'Topline & écriture',eyebrow:'Les mots',short_description:'Un refrain qui reste et des paroles à votre image.',description:'Création de toplines, paroles originales, arrangements vocaux et construction de la structure du morceau.',price_label:'Sur devis',price_unit:'/ selon la demande',features:['Topline','Paroles originales','Arrangements vocaux']},
 {slug:'clip-video',title:'Réalisation clip vidéo',eyebrow:'L’image',short_description:'Un clip pensé pour raconter votre morceau.',description:'Écriture du scénario, tournage, éclairage, montage, colorimétrie et effets visuels si nécessaires.',price_label:'À partir de 15 000 DA',features:['Scénario','Tournage & éclairage','Montage & étalonnage']},
]
export const packages = [
 {slug:'single-star',name:'Pack Single Star',tagline:'Tout l’essentiel pour un titre prêt à sortir.',price_label:'15 000 DA',compare_at_price:16000,items:['1h30 enregistrement vocal','1 beat personnalisé','Mixage & mastering professionnel'],badge:'Économisez 1 000 DA'},
 {slug:'hitmaker',name:'Pack Hitmaker',tagline:'Du premier couplet au hit radio.',price_label:'25 000 DA',items:['2h enregistrement vocal','1 beat personnalisé','Instruments live','Topline & arrangements vocaux','Mixage & mastering HD'],badge:'Le plus choisi'},
 {slug:'vip-artiste',name:'Pack VIP Artiste',tagline:'Le son et l’image dans une seule formule.',price_label:'À partir de 38 000 DA',items:['Pack Hitmaker','Tournage clip','Scénario & montage','Étalonnage','Export YouTube & réseaux']},
]
