'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { z } from 'zod'
import { createClient } from '@/lib/supabase/server'

const contactSchema = z.object({full_name:z.string().trim().min(2).max(120),artist_name:z.string().trim().max(120).optional(),phone:z.string().trim().min(6).max(40),email:z.union([z.literal(''),z.string().email()]).optional(),service_interest:z.string().max(120).optional(),message:z.string().trim().min(10).max(3000)})
export type FormState = {ok?:boolean;error?:string}
export async function sendContact(_prev:FormState,formData:FormData):Promise<FormState>{
 const parsed=contactSchema.safeParse(Object.fromEntries(formData))
 if(!parsed.success)return {error:'Vérifiez les champs indiqués puis réessayez.'}
 const supabase=await createClient()
 const {error}=await supabase.from('contact_messages').insert({...parsed.data,email:parsed.data.email||null,artist_name:parsed.data.artist_name||null,service_interest:parsed.data.service_interest||null})
 if(error)return {error:'Le message n’a pas pu être envoyé. Vous pouvez nous joindre directement par téléphone.'}
 return {ok:true}
}
export async function signIn(formData:FormData){const email=String(formData.get('email')||''),password=String(formData.get('password')||'');const supabase=await createClient();const {error}=await supabase.auth.signInWithPassword({email,password});if(error)redirect('/admin/login?error=credentials');redirect('/admin')}
export async function signOut(){const supabase=await createClient();await supabase.auth.signOut();redirect('/admin/login')}
export async function saveRecord(formData:FormData){const table=String(formData.get('table'));if(table!=='services'&&table!=='packages')return;const supabase=await createClient();const {requireAdmin}=await import('@/lib/admin');await requireAdmin();const id=String(formData.get('id')||'');const common={slug:String(formData.get('slug')),description:String(formData.get('description')||''),price_amount:formData.get('price_amount')?Number(formData.get('price_amount')):null,price_label:String(formData.get('price_label')),sort_order:Number(formData.get('sort_order')||0),is_active:formData.get('is_active')==='on'};const payload:Record<string,unknown>=table==='services'?{...common,title:String(formData.get('title')||''),eyebrow:String(formData.get('eyebrow')||''),short_description:String(formData.get('short_description')||''),price_unit:String(formData.get('price_unit')||''),features:String(formData.get('features')||'').split('\n').filter(Boolean)}:{...common,name:String(formData.get('name')||''),tagline:String(formData.get('tagline')||''),compare_at_price:formData.get('compare_at_price')?Number(formData.get('compare_at_price')):null,items:String(formData.get('items')||'').split('\n').filter(Boolean),badge:String(formData.get('badge')||'')||null,is_featured:formData.get('is_featured')==='on'};if(id)await supabase.from(table).update(payload as never).eq('id',id);else await supabase.from(table).insert(payload as never);revalidatePath('/');revalidatePath(`/admin/${table}`);redirect(`/admin/${table}`)}
export async function deleteRecord(formData:FormData){const table=String(formData.get('table'));if(table!=='services'&&table!=='packages')return;const {requireAdmin}=await import('@/lib/admin');const {supabase}=await requireAdmin();await supabase.from(table).delete().eq('id',String(formData.get('id')));revalidatePath(`/admin/${table}`)}
export async function updateMessage(formData:FormData){const {requireAdmin}=await import('@/lib/admin');const {supabase}=await requireAdmin();const id=String(formData.get('id')),status=String(formData.get('status'));if(!['new','read','replied','archived'].includes(status))return;await supabase.from('contact_messages').update({status}).eq('id',id);revalidatePath('/admin/messages')}
export async function removeMessage(formData:FormData){const {requireAdmin}=await import('@/lib/admin');const {supabase}=await requireAdmin();await supabase.from('contact_messages').delete().eq('id',String(formData.get('id')));revalidatePath('/admin/messages')}

const bookingSchema=z.object({full_name:z.string().trim().min(2).max(120),phone:z.string().trim().min(6).max(40),email:z.union([z.literal(''),z.string().email()]).optional(),service_interest:z.string().trim().min(2).max(120),starts_at:z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/),duration_minutes:z.coerce.number().int().min(30).max(480),message:z.string().max(2000).optional()})
export async function requestReservation(_prev:FormState,formData:FormData):Promise<FormState>{const parsed=bookingSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return {error:'Vérifiez les informations et choisissez une date et une heure futures.'};const startTime=new Date(`${parsed.data.starts_at}:00+01:00`);if(Number.isNaN(startTime.valueOf())||startTime<=new Date())return {error:'Choisissez un horaire qui n’est pas encore passé.'};const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('reservations').insert({...parsed.data,starts_at:startTime.toISOString(),user_id:user?.id||null,email:parsed.data.email||null,message:parsed.data.message||''} as never);if(error)return {error:'La demande n’a pas pu être enregistrée. Réessayez dans un instant.'};return {ok:true}}

const orderSchema=z.object({pack_slug:z.string().min(1).max(100),full_name:z.string().trim().min(2).max(120),phone:z.string().trim().min(6).max(40),email:z.union([z.literal(''),z.string().email()]).optional()})
export async function requestPack(_prev:FormState,formData:FormData):Promise<FormState>{const parsed=orderSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return {error:'Vérifiez votre nom, téléphone et e-mail.'};const supabase=await createClient();const {data:pack}=await supabase.from('packages').select('slug,name,price_label').eq('slug',parsed.data.pack_slug).eq('is_active',true).maybeSingle();if(!pack)return {error:'Ce pack n’est plus disponible. Contactez le studio.'};const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('pack_orders').insert({...parsed.data,user_id:user?.id||null,pack_name:pack.name,price_label:pack.price_label,email:parsed.data.email||null} as never);if(error)return {error:'La demande n’a pas pu être envoyée. Réessayez.'};return {ok:true}}

export async function updateReservation(formData:FormData){const {requireAdmin}=await import('@/lib/admin');const {supabase}=await requireAdmin();const id=String(formData.get('id')),status=String(formData.get('status'));if(!['confirmed','declined','cancelled'].includes(status))return;const {error}=await supabase.from('reservations').update({status} as never).eq('id',id);if(error)redirect('/admin/reservations?error=slot-conflict');revalidatePath('/admin/reservations');revalidatePath('/account')}
export async function updateOrder(formData:FormData){const {requireAdmin}=await import('@/lib/admin');const {supabase}=await requireAdmin();const id=String(formData.get('id')),status=String(formData.get('status'));if(!['confirmed','declined','completed','cancelled'].includes(status))return;await supabase.from('pack_orders').update({status} as never).eq('id',id);revalidatePath('/admin/orders');revalidatePath('/account')}
export async function signupUser(formData:FormData){const full_name=String(formData.get('full_name')||'').trim(),phone=String(formData.get('phone')||'').trim(),email=String(formData.get('email')||''),password=String(formData.get('password')||'');if(full_name.length<2||phone.length<6||password.length<10)redirect('/account/signup?error=invalid');const supabase=await createClient();const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name,phone}}});if(error){const detail=`${error.code||''} ${error.message}`.toLowerCase();console.error('Supabase signup failed:',error.code||'unknown',error.message);if(detail.includes('invalid api key')||detail.includes('invalid_api_key'))redirect('/account/signup?error=api_key');if(detail.includes('already registered')||detail.includes('already exists')||detail.includes('user_already_exists'))redirect('/account/signup?error=exists');if(detail.includes('password')||detail.includes('weak_password'))redirect('/account/signup?error=password');if(detail.includes('rate limit')||detail.includes('over_email_send_rate_limit'))redirect('/account/signup?error=rate');if(detail.includes('signup is disabled')||detail.includes('signups not allowed'))redirect('/account/signup?error=disabled');if(detail.includes('database error')||detail.includes('saving new user')||detail.includes('trigger'))redirect('/account/signup?error=database');redirect('/account/signup?error=signup')}redirect('/account/login?created=1')}
export async function userSignIn(formData:FormData){const supabase=await createClient();const {error}=await supabase.auth.signInWithPassword({email:String(formData.get('email')||''),password:String(formData.get('password')||'')});if(error)redirect('/account/login?error=credentials');redirect('/account')}
export async function saveProfile(formData:FormData){const {createClient}=await import('@/lib/supabase/server');const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/account/login');const full_name=String(formData.get('full_name')||'').trim(),phone=String(formData.get('phone')||'').trim(),email=String(formData.get('email')||'').trim();if(full_name.length<2||phone.length<6)redirect('/account?error=invalid');const {error}=await supabase.from('profiles').update({full_name,phone} as never).eq('user_id',user.id);if(error)redirect('/account?error=save');if(email&&email!==user.email){const {error:emailError}=await supabase.auth.updateUser({email});if(emailError)redirect('/account?error=email');revalidatePath('/account');redirect('/account?email=confirmation')}revalidatePath('/account');redirect('/account?saved=1')}
export async function userSignOut(){const supabase=await createClient();await supabase.auth.signOut();redirect('/')}
export async function manageUser(formData:FormData){const {requireAdmin}=await import('@/lib/admin');const {supabase,user}=await requireAdmin();const userId=String(formData.get('user_id')),role=String(formData.get('role')),is_active=formData.get('is_active')==='on';if(!userId||!['user','admin'].includes(role))return;if(userId===user.id&&(role!=='admin'||!is_active))return;await supabase.from('profiles').update({role,is_active} as never).eq('user_id',userId);if(role==='admin')await supabase.from('admin_users').upsert({user_id:userId} as never);else await supabase.from('admin_users').delete().eq('user_id',userId);revalidatePath('/admin/users')}
export async function createManagedUser(formData:FormData){const {requireAdmin}=await import('@/lib/admin');await requireAdmin();const email=String(formData.get('email')||'').trim(),password=String(formData.get('password')||''),full_name=String(formData.get('full_name')||'').trim(),phone=String(formData.get('phone')||'').trim(),role=String(formData.get('role')||'user');if(!email||password.length<10||full_name.length<2||!['user','admin'].includes(role))redirect('/admin/users?error=invalid');const {createAdminClient}=await import('@/lib/supabase/admin');let serviceClient;try{serviceClient=createAdminClient()}catch{redirect('/admin/users?error=service_key')}const {data,error}=await serviceClient.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name,phone}});if(error||!data.user)redirect('/admin/users?error=create');const studioDb=serviceClient.schema('studio-music');await studioDb.from('profiles').update({role} as never).eq('user_id',data.user.id);if(role==='admin')await studioDb.from('admin_users').upsert({user_id:data.user.id});revalidatePath('/admin/users');redirect('/admin/users?created=1')}
